services:
  mysql-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=my_pwd
    ports:
      - 3306:3306
    networks:
      - cp4-networks
  api:
    depends_on:
      - mysql-db
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_DATABASE=api
      - DB_USER=root
      - DB_PASSWORD=root_pwd
    networks:
      - cp4-networks

networks:
  cp4-networks: